//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 3d4198ac-d4a7-46cc-bb09-b9cfccef5a43 aws-my-sample-app-android-v0.10";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("ap-northeast-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "ap-northeast-1:9bb1e97f-4076-4927-ae63-b1694486ff11";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "c8a0e9d1e974423a8976398b2b27928c";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "823346103645";

    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:ap-northeast-1:652452812043:app/GCM/wodriver_MOBILEHUB_1034201032";
    public static final Regions AMAZON_SNS_REGION =
         Regions.fromName("ap-northeast-1");
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:ap-northeast-1:652452812043:wodriver_alldevices_MOBILEHUB_1034201032";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {};
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "wodriver-contentdelivery-mobilehub-1034201032";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("ap-northeast-1");
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "wodriver-userfiles-mobilehub-1034201032";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("ap-northeast-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "ap-northeast-1_eIYXtL0lW";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "5siu808vukup4imd21t5c7ne1s";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "geehcbsuvh6r4h0jg7a85u5rkdig9crndi0ar9853e8sbmfnu7h";
}
